### ISSUE TITLE
Close button is too close to the edge 

### ISSUE THREAD

**Issue by arshubham** [Zonnev/elementaryos-firefox-theme#4]
Firefox 67.0.a1

The maximize button, however is at correct distance.

![image](https://user-images.githubusercontent.com/14235191/52724170-d71bb400-2fd4-11e9-8518-ef77e44deb8f.png)

**Comment by Zonnev** [comment]
Hello, I will adjust this when 67 is released. Firefox 65 is a bit different than 67.

**Comment by arshubham** [comment]
Just for reference using fixes the issue
```css
.titlebar-close {
  margin-left: 5px !important;
}
```
